// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Flex_TEST.Models
{
    public partial class MemberPoints
    {
        public int MemberPointsId { get; set; }
        public int PointSubtotal { get; set; }
        public int fk_PointHistoryId { get; set; }
        public int fk_MemberId { get; set; }

        public virtual Members fk_Member { get; set; }
        public virtual PointHistories fk_PointHistory { get; set; }
    }
}